### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by gdau** [alexive/visual-goodies#1]
Hi!

This looks great - nicely done. Do you perhaps have a sample project that can be added that demonstrates the features of this library?

Cheers!

g

**Comment by alexive** [comment]
Hey!

Thanks! About the sample project, I have already thought about that and I'll start working on one ASAP. But what is the best practice, to add it as new module or create a whole new repository?

**Comment by gdau** [comment]
I think it's best to keep it within the same repo - most libs with a sample seem to have it as a seperate project in the root - take look at this one:

[butterknife git repo](https://github.com/JakeWharton/butterknife)

He has the "butterknife-sample" project at the root.

Cheers again for this project :)

g

**Comment by SubhrajyotiSen** [comment]
Looking forward to the sample project  :)

**Comment by alexive** [comment]
I've already started creating a sample project. If all goes as planned, I'll be uploading it in a few hours :relieved:
